#regionlar manuel olarak biz belirledik.
cities_regions = {
    "Aachen": "NRW",
    "Albuquerque": "NM",
    "Anchorage": "AK",
    "Barcelona": "CAT",
    "Barquisimeto": "LAR",
    "Bergamo": "LOM",
    "Berlin": "BER",
    "Bern": "BE",
    "Boise": "ID",
    "Brandenburg": "BB",
    "Bruxelles": "BRU",
    "Bräcke": "VG",
    "Buenos Aires": "BA",
    "Butte": "MT",
    "Campinas": "SP",
    "Caracas": "DC",
    "Charleroi": "WL",
    "Cork": "Co. Cork",
    "Cowes": "IW",
    "Cunewalde": "SN",
    "Elgin": "OR",
    "Eugene": "OR",
    "Frankfurt a.M.": "HE",
    "Genève": "GE",
    "Graz": "ST",
    "Helsinki": "UU",
    "I. de Margarita": "NE",
    "Kirkland": "WA",
    "Kobenhavn": "Hovedstaden",
    "Köln": "NRW",
    "Lander": "WY",
    "Leipzig": "SN",
    "Lille": "HDF",
    "Lisboa": "LIS",
    "London": "ENG",
    "Luleå": "BD",
    "Lyon": "ARA",
    "Madrid": "M",
    "Mannheim": "BW",
    "Marseille": "PACA",
    "Montréal": "QC",
    "México D.F.": "CDMX",
    "München": "BY",
    "Münster": "NRW",
    "Nantes": "PDL",
    "Oulu": "OUL",
    "Paris": "IDF",
    "Portland": "OR",
    "Reggio Emilia": "ER",
    "Reims": "GE",
    "Resende": "SP",
    "Rio de Janeiro": "RJ",
    "Salzburg": "SAL",
    "San Cristóbal": "TAC",
    "San Francisco": "CA",
    "Sao Paulo": "SP",
    "Seattle": "WA",
    "Sevilla": "AN",
    "Stavern": "VF",
    "Strasbourg": "GE",
    "Stuttgart": "BW",
    "Torino": "PIE",
    "Toulouse": "OCC",
    "Tsawassen": "BC",
    "Vancouver": "BC",
    "Versailles": "IDF",
    "Walla Walla": "WA",
    "Warszawa": "MAZ",
    "Århus": "HOVEDSTADEN"
}